/** @type {import('tailwindcss').Config} */
export default {
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'secondary-fixed': '#dbe1ff',
        'outline-variant': '#c5c6cd',
        'primary-fixed-dim': '#bac7e1',
        'surface-container': '#e5eeff',
        'surface-tint': '#525f75',
        'on-primary-fixed': '#0e1c2f',
        outline: '#75777d',
        secondary: '#0051d5',
        'surface-container-low': '#eff4ff',
        'on-surface-variant': '#44474c',
        tertiary: '#000000',
        'on-tertiary-fixed': '#00201d',
        'inverse-surface': '#213145',
        'on-error-container': '#93000a',
        'surface-container-high': '#dce9ff',
        'tertiary-container': '#00201d',
        'primary-container': '#0e1c2f',
        'surface-container-lowest': '#ffffff',
        'tertiary-fixed-dim': '#6bd8cb',
        'on-secondary-fixed-variant': '#003ea8',
        'on-secondary-container': '#fefcff',
        'on-tertiary': '#ffffff',
        'secondary-fixed-dim': '#b4c5ff',
        'surface-variant': '#d3e4fe',
        'surface-dim': '#cbdbf5',
        'on-surface': '#0b1c30',
        error: '#ba1a1a',
        'surface-bright': '#f8f9ff',
        primary: '#000000',
        'on-tertiary-fixed-variant': '#005049',
        'on-primary': '#ffffff',
        'secondary-container': '#316bf3',
        'on-secondary-fixed': '#00174b',
        'on-primary-container': '#77849c',
        'on-secondary': '#ffffff',
        'error-container': '#ffdad6',
        'on-tertiary-container': '#0c9488',
        'inverse-on-surface': '#eaf1ff',
        'on-background': '#0b1c30',
        'inverse-primary': '#bac7e1',
        'tertiary-fixed': '#89f5e7',
        background: '#f8f9ff',
        surface: '#f8f9ff',
        'primary-fixed': '#d6e3fe',
        'on-primary-fixed-variant': '#3a475c',
        'on-error': '#ffffff',
        'surface-container-highest': '#d3e4fe',
      },
      borderRadius: { DEFAULT: '0.25rem', lg: '0.5rem', xl: '0.75rem', full: '9999px' },
      spacing: {
        'gutter-tablet': '1.5rem', 'gutter-mobile': '1rem', 'space-sm': '0.75rem', 'space-xs': '0.5rem',
        'space-xl': '2rem', 'space-4xl': '6rem', 'container-max': '80rem', 'space-2xl': '3rem',
        'gutter-desktop': '2rem', 'space-3xl': '4rem', 'space-md': '1rem', 'space-2xs': '0.25rem', 'space-lg': '1.5rem',
      },
      fontFamily: {
        'body-lg': ['"Plus Jakarta Sans"', 'sans-serif'], 'headline-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-xl-mobile': ['"Plus Jakarta Sans"', 'sans-serif'], 'body-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'display-hero-mobile': ['"Plus Jakarta Sans"', 'sans-serif'], 'display-hero': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-xl': ['"Plus Jakarta Sans"', 'sans-serif'], 'label-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-sm': ['"Plus Jakarta Sans"', 'sans-serif'], 'headline-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-sm': ['"Plus Jakarta Sans"', 'sans-serif'], 'headline-xl': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-sm': ['"Plus Jakarta Sans"', 'sans-serif'], 'label-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-xl-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'display-hero-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-hero': ['56px', { lineHeight: '64px', letterSpacing: '-0.025em', fontWeight: '800' }],
        'body-xl': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '700' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-sm': ['20px', { lineHeight: '28px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
